###############
## 
####

GPU: [3]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'IHRFNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 32
  NUM_EPOCHS: 120
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128 #128
  VAL_PS: 256
  TRAIN_DIR: '/workspace/Datasets/train' # path to training data
  VAL_DIR: '/workspace/Datasets/val'     # path to validation data
  SAVE_DIR: '/workspace/checkpoints'          # path to save models and images
  # SAVE_IMAGES: False
